name: Generate README and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Déclenche l'action lorsqu'un push est effectué sur la branche "main"
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

permissions:
  contents: write  # Accorder les permissions d'écriture sur les contenus du dépôt

jobs:
  generate-readme-and-doc:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Choisissez la version de Node.js souhaitée

      # Créer le script pour générer le README.MD
      - name: Generate README.MD
        run: |
          echo "const fs = require('fs');" > generateReadme.js
          echo "const packageJson = require('./package.json');" >> generateReadme.js
          echo "const { name, displayName, version, description, author, dependencies } = packageJson;" >> generateReadme.js
          echo "let dependenciesContent = '**Dependencies**:';" >> generateReadme.js
          echo "for (const [key, value] of Object.entries(dependencies)) {" >> generateReadme.js
          echo "  dependenciesContent += \`\n-\${key} : \${value}\`;" >> generateReadme.js
          echo "}" >> generateReadme.js
          echo "const readmeContent = \`# \${name}\n\n## \${displayName} : \${version}\n\n\${description}\n\n\${dependenciesContent}\n\n\${author.name}\n\n\${author.email}\n\n\${author.url}\`;" >> generateReadme.js
          echo "fs.writeFileSync('README.MD', readmeContent);" >> generateReadme.js
          node generateReadme.js

      # Vérifier si le fichier README.MD a changé
      - name: Check for README changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.MD
            git commit -m "Update README.MD"
            git push
          else
            echo "No changes to commit"
          fi

      # Installer Doxygen
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      # Générer la documentation avec Doxygen
      - name: Generate Doxygen documentation
        run: doxygen DoxygenConfig

      # Configurer Git pour le déploiement
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Déployer la documentation sur la branche gh-pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utiliser le GITHUB_TOKEN pour l'authentification

        run: |
          # Créer un répertoire temporaire pour le déploiement
          mkdir -p ../gh-pages
          cp -r ./Documentation/* ../gh-pages/

          # Passer dans le répertoire gh-pages
          cd ../gh-pages

          # Initialiser un dépôt Git et ajouter les fichiers
          git init
          git add .
          git commit -m "Deploy Doxygen documentation"

          # Forcer le push vers la branche gh-pages
          git branch -M gh-pages
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages
